server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: cambio-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: tvf8$k6k
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  management:
    tracing:
      sampling:
        probability: 1.0
    zipkin:
      tracing:
        endpoint: http://zipkin:9411/api/v2/spans
springdoc:
  api-docs:
    path: /cambio-service/v3/api-docs